site_name: meta - dafnik.me
site_url: https://meta.dafnik.me
site_author: Dafnik

repo_name: dafnik/meta
repo_url: https://gitlab.com/dafnik/meta

dev_addr: '127.0.0.1:8080'

theme:
  favicon: img/favicon.png
  name: 'material'
  palette:
    scheme: 'slate'
    primary: 'blue grey'
    accent: 'amber'

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime

markdown_extensions:
  - codehilite
  - admonition

nav:
    - Home: index.md
    - Scripts:
        - Certbot get certificate: scripts/certbot-get-certificate-with-nginx-hooks.md
        - Git file mode changes: scripts/disable-git-file-mode-changes.md
        - Mirror online directory: scripts/mirror-online-dir.md
    - Fixes:
        - Export chrome bin: fixes/export-chrome-bin.md
        - GitKraken pre commit fix: fixes/kraken-pre-commit-hook-fails.md